### PR TITLE
Expose environment into a command template

### PR DESCRIPTION
**Pull request by konradekk**
hi! nicely done this plugin here of yours!

i’d like to have environment variables passed into the template—i thought i prepare a pr for you to speed up things (discussions, merger, deployment etc.)… i’d happily give more details or amend the pr if needed.

cheers!

### CODE REVIEW

**Comment by hasezoey** [comment]
sorry to ask this, but any news from an maintainer on this PR?

**Comment by konradekk** [comment]
He apparently shows up from time to time, I guess. But it’s more like once a year or so than every two weeks… So here, it seems we still have roughly ca. half a year. ;)

Be patient or… just fork that! (I did not tested that—so feel free to tell how it went etc.! Thanks in advance for the feedback!)

**Comment by hasezoey** [comment]
> I did not tested that—so feel free to tell how it went etc.! Thanks in advance for the feedback!

for my use-case i just ended up using an command that directly takes an environment variable from the environment (for completing it was `semantic-release-rust`)

**Comment by konradekk** [comment]
Neat! I don’t want to invest time for that if it won’t be used—and it seems it won’t as there’s quite a big lag regarding any kind of interaction with the maintainer(s)… 😅

**Comment by konradekk** [comment]
Is this anyhow needed for anybody? 🤔

**Comment by hasezoey** [comment]
> Is this anyhow needed for anybody? thinking

i am currently not "requiring" this, but this would probably be useful, because currently you either had the wanted program to have environment variables, or required to wrap the command in a script

**Comment by cj81499** [comment]
@konradekk Why did you close this? It'd be a positive change to the tool imo.

**Pull request closed without merging**
